apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: venkatmongo
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
    - port: 9631
      targetPort: 9631
      name: habsup
  selector:
    name: mongo
