apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  containers:
  - image: kbhimanavarjula/mongodb:latest
    name: mongo
    env:
    - name: HAB_MONGODB
      value: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
    ports:
    - name: mongo
      containerPort: 27017
      hostPort: 27017
    - name: habsup
      cointainerPort: 9631
      hostPort: 9631
      

