apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: npapp
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: kbhimanavarjula/nptest:latest
        name: web
        ports:
        - name: np-app
          containerPort: 8080
          hostPort: 8080
        - name: habsup
          containerPort: 9631
          hostPort: 9631
        - name: mongodb
          containerPort: 27017
          hostPort: 27017
          
