apiVersion: v1
kind: Pod
metadata:
  labels:
    name: web
  name: npapp
spec:
  containers:
  - image: kbhimanavarjula/national-parks:latest
    name: web
    args:
      - "--peer"
      - "mongo" # Main command to run
      - "--bind"
      - "database:national-parks.default" # Args passed to that main command
    ports:
    - name: np-app
      containerPort: 8080
    - name: habsup
      containerPort: 9631
    - name: mongodb
      containerPort: 27017
      

